### ISSUE TITLE
Doesn't address how to fix the issue when this message pops up and there's no other user account logged in

### ISSUE THREAD

**Issue by BobSmiley** [MicrosoftDocs/OfficeDocs-Support#897] opened 2020-11-06 17:25 UTC
The document says something on the order of "this is expected behavior because only one login from the same tenant can be logged in at a time."  So--that's the expected behavior, but it doesn't address the situation when this message pops up and that is not the case.

I am the only user of my computer.  I log in to different client tenants because I'm a consultant.  This message has started popping up recently when i try to access a document via Teams; but if i access it by opening word directly, i don't get this message.  Your document needs to explain whether the workaround is intended for this situation, or if there's a different set of troubleshooting steps that needs to be addressed.

Troubleshooting documentation that assumes the software is working flawlessly is not only short-sighted, it's arrogant and demeaning to the users who are reading it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6baec64-2c8f-ed19-b498-369711b79dc3
* Version Independent ID: f2cb07f9-d352-73a5-4351-138f2e71cd9b
* Content: [Another account is already signed in computer when signing in to Office 2013 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/another-account-already-signed-in)
* Content Source: [Office/Client/office-suite-issues/another-account-already-signed-in.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/another-account-already-signed-in.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment] 2021-05-19 01:30
@BobSmiley Thank you for your feedback. This document applies to outlook 2013. If you are the latest version of outlook, the registry key to clear the identities would be HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\Identity\Identities.

Also, the document applies if the cause is due to another account is already signed in to Office 2013 by using a different Office 365 user account within the same organization/tenant. So the issue you are facing could be different if the user accounts are from different tenants.

Hope this helps!

Thanks
Sri

**Comment by BobSmiley** [comment] 2021-05-19 02:05
@msbemba Thank you for your reply, and for the updated link for my version. (That part was straight forward.) I'm afraid I didn't make clear the issue I'm having, and perhaps you'll better understand the issue if I can explain it better.  I mentioned that I have to sign in to multiple tenants; this is true, but it's not the issue.  I said that because it might provide context to how the real issue comes about.

I get this message often when attempting to open a file on OneDrive.  I'm already logged in as a user of that tenant in another app, say OneDrive or Word/Excel, but when I use Teams to launch word or excel to open a file, I get prompted again for the login to the same tenant.  When I provide my credentials, I get the message saying "another user is already logged in".  My point is, that "other user" is me!  With the same credentials!

Following these instructions doesn't solve that problem, because there's no way for me to avoid the login dialog.  The code must be checking for *any* other login, rather than validating that the other login it sees is truly a different login.

I suspect there's a defect hidden in here--possibly a design defect if not a code defect.  Someone has designed this so that it isn't rock solid when it comes to using multiple apps.  Possibly the issue is with the apps rather than the credential module, but somewhere there's an issue preventing some of us from being effective with your tools, because you're requiring us to log in, and preventing us from doing so, when we are already logged in in the first place.

**Comment by msbemba** [comment] 2021-05-19 20:11
@BobSmiley Thank you for the additional information. The issue that you are facing is different from what is addressed in the document. The issue you have occurs due to the one drive application. I could not find a document which talks about it, however, the fix would be clear "use office applications to sync files that I open". The issue happens when there are multiple accounts in your machine and one drive does not know which one to sync the file with.

![image](https://user-images.githubusercontent.com/45987684/118877626-4ac36e80-b90c-11eb-8673-c65480374ace.png)

Hope this helps!

Thanks
Sri

**Comment by BobSmiley** [comment] 2021-05-21 17:34
Thank you again for your reply.  After I had sent you my reply, I racked my brain to figure out how I even submitted anything, and I recalled that I was commenting on the document itself, not realizing I was reporting a problem.  In this complex technology world, the behavior of one product is affected by others in ways that only the developers know.  If you could figure out a way to include a statement like this in that document, I bet it would be helpful to a sizable percentage (though still a minority) of your users who have this error message displayed to them.

And thank you very much for the recommendation.  I’ll turn that off right now and hope for the best.

Regards,
Bob Smiley
Independent Consultant
IT Strategy and Implementation
(925) 789-9238  Direct/Text

**Comment by nam31** [comment] 2021-05-28 15:40
@BobSmiley Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by nam31** [comment] 2021-05-28 16:39
@BobSmiley Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-05-28 16:39 UTC
Labels: CI created
