### ISSUE TITLE
This page is out of date and incorrect.

### ISSUE THREAD

**Issue by sanga549** [MicrosoftDocs/OfficeDocs-Support#163] opened 2019-10-15 19:33 UTC
I need to turn off Office 2013 update prompts users receive using Office 2013 on Citrix. This document says to edit the registry using the following path:

Office 2013
HKEY_LOCAL_MACHINE\software\policies\microsoft\office\15.0\common\OfficeUpdate

Problem is there is no 'office' key in the provided path HKEY_LOCAL_MACHINE\software\policies\microsoft\????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49136300-9a11-ce51-3830-cf8bba44f881
* Version Independent ID: 8a0dd569-5d49-cdc7-c903-38ff685261c5
* Content: [Automatic updating for Office 2016 and 2013 Click-to-Run is not enabled - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/automatic-updates#feedback)
* Content Source: [Microsoft365/admin/administration/automatic-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/automatic-updates.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by VLG17** [comment] 2021-06-03 14:02
@sanga549 I've checked and I see it on my Windows 10 / Office 365 setup. Are you testing on a shared environment, or your own? Can you share some details about your setup?

![image](https://user-images.githubusercontent.com/41186174/120657573-4b700f00-c48d-11eb-8d5e-76241509b35f.png)

**Comment by nam31** [comment] 2021-06-11 17:47
@sanga549 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by nam31** [comment] 2021-06-11 17:47
@sanga549 can you please share your inputs?

**Comment by nam31** [comment] 2021-06-14 10:39
@sanga549 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-06-14 10:39 UTC
Labels: CI created

**Comment by sanga549** [comment] 2021-06-15 04:46
Hello there. My inquiry was posted in almost 2 years ago. I appreciate the returned inquiry/support but I got past this problem since then.  Thanks again.
