### ISSUE TITLE
Possible error in: "How to determine whether a year is a leap year"

### ISSUE THREAD

**Issue by NewbieWanKenobi** [MicrosoftDocs/OfficeDocs-Support#493] opened 2020-04-25 15:06 UTC
Should the following step:
2. If the year is evenly divisible by 100, go to step 3. Otherwise, go to step 5.

Not be:
2. If the year is evenly divisible by 100, go to step 3. Otherwise, go to step 4.

The condition: "Otherwise, go to step 5." will result in 1992 is NOT a leap year

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year#feedback)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nk-gears** [comment] 2021-06-05 15:10
Hello @NewbieWanKenobi,

Thanks for reporting this issue. We have noted down the wording issue about leap year.

Will update you in few days.

**Comment by nk-gears** [comment] 2021-06-09 04:14
@nam31 We can close this Ticket as the document has been fixed already.

**Comment by nam31** [comment] 2021-06-14 07:38
@NewbieWanKenobi Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-06-14 07:38 UTC
Labels: CI created
