### ISSUE TITLE
incorrect assumption

### ISSUE THREAD

**Issue by burtzz** [MicrosoftDocs/OfficeDocs-Support#993] opened 2020-12-17 11:09 UTC
Hi, can you please review this part of the article?

If the domain's primary MX record can't be pointed to EOP, EOP will automatically detect when it's not the primary MX record and stop enforcing the ASF option for SPF hard fail. When the MX record points to EOP, the service detects this and starts enforcing the ASF option.

My tenant complies with the above scenario, I do not point our MX records to EOP.
Nonetheless, enabling this feature had a huge impact on incoming email flow. A lot of valid email being sent to the junk folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c9cf4b-8641-c48e-6413-3a6c3b9c5672
* Version Independent ID: a8459122-13d6-8258-c329-279ccbdbc613
* Content: [Lots of false positives are generated when the SPF record hard fails advanced spam filtering option is enabled. - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/antispam/false-positives)
* Content Source: [Microsoft365/security/antispam/false-positives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/security/antispam/false-positives.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment] 2021-05-24 06:41
Hello @burtzz,
how is your mail flow configured? internet->on-prem -> EOP?
**A lot of valid email being sent to the junk folder** - are you sure it is caused by ASF?
Thank you

**Comment by MaratMussabekov** [comment] 2021-05-24 06:48
Hello @burtzz,
how is your mail flow configured? internet->on-prem -> EOP?
**A lot of valid email being sent to the junk folder** - are you sure it is caused by ASF?
Thank you

**Comment by MaratMussabekov** [comment] 2021-06-01 15:13
Hello @burtzz,
Did you have time to check it?
Thank you

**Comment by nam31** [comment] 2021-06-07 11:56
@burtzz We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-06-07 11:56 UTC
Labels: CI created
