### ISSUE TITLE
Cannot Licence Office

### ISSUE THREAD

**Issue by alexishughes** [MicrosoftDocs/OfficeDocs-Support#773] opened 2020-09-07 16:02 UTC
[Enter feedback here]
Hi I have tried every step on this thread. Each time I try to licence Office (Word or Outlook) for 365 I am presented with a blank white square where the password box should be. Other than reinstalling Windows, I am out of ideas.

I also used the Office tool to completely remove all office installations.

You might be interested in this issue. Not sure how to reproduce,

I guess I will have to reinstall Windows within 24 hours max as email cannot be used.

Thanks for your thread,

Alexis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Microsoft 365 Apps for enterprise activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by RAJU2529** [comment] 2020-09-07 16:40
@alexishughes , You can use  this **Microsoft Support and Recovery Assistant** tool, which can be downloaded from 

**https://support.microsoft.com/en-us/office/about-the-microsoft-support-and-recovery-assistant-e90bb691-c2a7-4697-a94f-88836856c72f**

or  from 

**https://www.microsoft.com/download/100607**

**Comment by alexishughes** [comment] 2020-09-07 20:54
Thanks, @RAJU2529, I will try this tomorrow. I'll read up on it tonight and let you know how it goes.

**Comment by alexishughes** [comment] 2020-09-07 21:07
All I can say about reproducing the issue is:

There may have been multiple Office Installs including 8, 15 an 16 which I hoped I had removed using a tool downloaded from you.

There could be issues with the Office365 ID being changed more than once.

I did this because I was Migrating to 365 from a POP only server and basically had to keep email connected until the DNS MX records were changed, then drag and drop any new emails (cutover maigration was not possible as no IMAP access was available) however, I discovered Outlook 365 will not permit two folders for the same email address (maybe it should).

The start button on Windows 10 (fairly recent install) would not even respond at one time - no obvious explanation but worked-around by restarting.

AVG antivirus was installed.

I had moved .pst files to prevent them being erased on Outlook account deletion because time was pressured and I did not have available time to copy - then did copy them but to no avail.

In the end, I just wanted to licence Outlook and reopen 49GB of archive folders that could not be uploaded using AzCopy.exe because there is seemingly no easy way to break them into <20GB chunks (I had even tried downloading faulty (although signed) third party software to split .psts).

I left this email client with Outlook on the Web and no archives - though 2 copies of the Archives remain intact.

**Comment by alexishughes** [comment] 2020-09-08 07:47
@RAJU2529, The tool did not work. We are still presented with a white square where password info should be entered.

**Comment by RAJU2529** [comment] 2020-09-08 09:14
@alexishughes . in that square box, will you able to enter the password ? and office connects to server for verification.

**Comment by MJP-MSFT** [comment] 2020-09-08 12:17
Hello Folks!

Sorry for the delay I was out of office for a few days.  As far as the square blank box I have seen this before. It is caused by having policies enabled that block signing into office and force the sign in box to not show any information. 

Please check for the GPO or Reg Key called SigninOptions or UseOnlineContent. Remove those and you should be good to go.

**Comment by nam31** [comment] 2021-05-23 13:47
@alexishughes this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment] 2021-05-27 17:22
@alexishughes We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-05-27 17:22 UTC
