### ISSUE TITLE
When will this be corrected?

### ISSUE THREAD

**Issue by jackvinson** [MicrosoftDocs/OfficeDocs-Support#762] opened 2020-09-02 17:31 UTC
[Enter feedback here]
Would love to know when this is resolved.  It seems to be a similar problem with meeting platforms.  One can use the web-based version of Teams and a virtual camera, but those don't work as nicely with the other Teams features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cf7387-cb88-9098-5eb5-5ee64ae6e432
* Version Independent ID: 276073a5-ac13-3804-a0d5-ab705a52957b
* Content: [Virtual camera on MacOS Teams stops working - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-on-mac/virtual-camera-doesnt-work-macos)
* Content Source: [Teams/teams-on-mac/virtual-camera-doesnt-work-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-on-mac/virtual-camera-doesnt-work-macos.md)
* Service: **msteams**
* GitHub Login: @McCoyBot
* Microsoft Alias: **v-todmc**

**Comment by aleksandrs-ledovskis** [comment] 2020-12-20 11:46
A workaround is to remove code signature on Teams client - dirty, but hey, it works.

https://github.com/johnboiles/obs-mac-virtualcam/issues/171#issuecomment-728255352

**Comment by sprocketphysics** [comment] 2020-12-28 03:08
Yes, we need virtual camera!

**Comment by lgaj6085** [comment] 2021-02-04 09:07
Guys, it's been months. Zoom has managed to get this working - why can't you?

**Comment by astrostl** [comment] 2021-02-04 14:04
Definitely feels odd to be unsigning app store binaries.

**Comment by jackvinson** [comment] 2021-02-04 14:21
Agreed - why should we need to break binaries to get this capability?  I can confirm that it works.  Of course, when Teams updates, it seems I need to re-apply these changes.

For what it's worth, there is a similar problem with the Webex desktop application on MacOS.  (I haven't investigated what is required to enable virtual cameras with Webex.)

**Comment by steinmb** [comment] 2021-02-15 11:34
No updates or fix, sounds like Microsoft. Fix it or make a native MacOS application not this half ass web application Electron crap: `find /Applications -type d -name "*Electron Framework.framework" | cut -d/ -f3`

**Comment by bananaman2020** [comment] 2021-03-09 12:13
Hey, I've developed a script to fix this. The problem is the code signature in Teams not allowing the virtual cam if you go into my repo bananaman2020/teamsvcam download the script and run it. That will fix the virtual camera issue as it will allow unsigned devices to communicate.

**Comment by nam31** [comment] 2021-05-23 13:41
@jackvinson this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by astrostl** [comment] 2021-05-23 15:21
Article?

**Comment by nam31** [comment] 2021-05-27 17:22
@jackvinson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-05-27 17:22 UTC

**Comment by jackvinson** [comment] 2021-05-28 13:32
This is not a high-prioirty issue for me.  However, **the issue seems to be resolved!**  Yay!

Specifically, I had to ensure Teams had the latest updates which appear to be from 25 May.  Then I had to close and reopen both Teams and the virtual camera application several times.  And probably restart my computer.  (Initially, when I received this update I saw that it wasn't working.)
