### ISSUE TITLE
EAS does not appear to be supported for "other services"

### ISSUE THREAD

**Issue by dofzin** [MicrosoftDocs/OfficeDocs-Support#789] opened 2020-09-14 16:59 UTC
The article states "Outlook supports the use of EAS to connect to other services that support the EAS protocol." But the article does not state how to configure a service that does support EAS, such as Gmail. When adding a Gmail account in Outlook, the user flow defaults to an IMAP connection, and the connection type cannot be changed by the user. In contrast, adding a Gmail account on Outlook for Android or iOS uses EAS, as expected.

It is clear that Outlook desktop does not support EAS connections to Exchange, but the claim that Outlook supports EAS to OTHER services is either incorrect or too poorly documented to be used. As this article claims that Outlook desktop supports the use of EAS, it needs to explain how to achieve that or provide links to other articles that do so. If Outlook desktop in fact does not supports EAS for any (non-Microsoft) services, the article should be corrected to so state that Microsoft has dropped support for EAS and provide a workaround for seamlessly syncing mail, calendar, and contacts data for EAS services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2edf04-9faf-cda3-3fbe-d03f43af1e94
* Version Independent ID: c847dc97-09f8-3499-60ee-fb9c5ba80d8f
* Content: [Outlook can't use ActiveSync to connect Exchange - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/outlook-cannot-use-activesync-connect-exchange)
* Content Source: [Outlook/Client/profiles-and-accounts/outlook-cannot-use-activesync-connect-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/outlook-cannot-use-activesync-connect-exchange.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment] 2021-05-23 13:57
@dofzin this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment] 2021-05-27 17:23
@dofzin We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by dofzin** [comment] 2021-05-27 18:27
Sorry, I'm not seeing the change you are referencing. The article still states "Outlook supports the use of EAS to connect to other services that support the EAS protocol." And yet I find it impossible to configure a Gmail account in a way that does not use IMAP. Where are the instructions for connecting to non-Exchange servers using the EAS protocol? Other than claiming that Outlook on the desktop supports EAS, I can find nothing about configuring such a connection in the article, nor does the article link to another that does. Please explain the basis for the sentence "Outlook supports the use of EAS to connect to other services that support the EAS protocol."

**Comment by dofzin** [comment] 2021-05-27 18:42
@nam31 since I am not a collaborator, I can't reopen the issue. Please reopen as this is not resolved. I believe what this article should do is explain that to use EAS with a non-Exchange account, you must first follow the steps to make the registry edits included in this article: https://support.microsoft.com/en-us/topic/how-to-disable-simplified-account-creation-in-outlook-2016-outlook-2019-and-outlook-for-office-365-662bf4f8-c357-dbc8-53b3-ff8f445e8247 although I have not tested that solution to see if it does indeed work.

**Comment by MaratMussabekov** [comment] 2021-07-10 16:30
Hello @dofzin ,
**And yet I find it impossible to configure a Gmail account in a way that does not use IMAP.** - only paid gmail (as part of the Google Workspace subscription) supports EAS.
**Where are the instructions for connecting to non-Exchange servers using the EAS protocol?** - the configuration varies. It is up to service providers that use EAS to publish instructions
**Other than claiming that Outlook on the desktop supports EAS, I can find nothing about configuring such a connection in the article, nor does the article link to another that does.** - there is no such article in microsoft docs, since no Microsoft service supports EAS on desktop outlook (Outlook.com/Hotmail used to support it, now they are using MAPI over HTTPS, like Exchange Server).
**Please explain the basis for the sentence "Outlook supports the use of EAS to connect to other services that support the EAS protocol."** - examples of services that do support EAS could be found [here](https://en.wikipedia.org/wiki/Exchange_ActiveSync#Usage).
Thank you

**Comment by nam31** [comment] 2021-07-19 17:42
@dofzin Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-19 17:42 UTC
Labels: CI created
