### ISSUE TITLE
Re: "Office Products Troubleshooting" page - add list of products covered. 

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-Support#102] opened 2019-08-26 17:21 UTC
The page is rather blank. It would be nice if you listed the programs / products covered as hyperlinks. That way we could copy the list for our own notes so we know what is covered without having to retype the list. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32302b9a-4180-2d90-c160-f8bbb00420fc
* Version Independent ID: 1a05b7a2-9495-fcd2-16a3-480ba82a8c20
* Content: [Listing some issues for Office products. - Office](https://docs.microsoft.com/en-gb/office/troubleshoot/client)
* Content Source: [Office/Client/client.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/client.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment] 2019-08-26 23:57
Every article in the TOC has the applied products displayed on the top of the page.

**Comment by Ronsss** [comment] 2019-08-27 00:29
That is not what I'm talking about.  If you had bothered to look at the page you would see that it is essentially blank.

I've screen cap'd it.  What I was asking for was to include the stuff highlighted in yellow as hyperlinked text in the body of the page.  I like to copy stuff like that into my personal notes so I when I'm searching for help/tips, I know what is on the page without having to go to it every time.

And the same for each of the header pages.

[zzz.png]

On Mon, Aug 26, 2019 at 6:57 PM Simonx Xu <notifications@github.com<mailto:notifications@github.com>> wrote:

Every article in the TOC has the applied products displayed on the top of the page.

**Comment by Ronsss** [comment] 2019-08-27 03:42
You keep mentioning the articles. I am not talking about the individual articles. I am talking about the TOC pages, for the whole subject, specifically the overall TOC shown in the screen capture:
https://docs.microsoft.com/en-gb/office/troubleshoot/client

There are no sub topic TOCS, the section of the screen cap highlighted in yellow. But there are on some topics in this sub site, ie

https://docs.microsoft.com/en-us/office/vba/api/word(enumerations)

I've drawn you a picture, what more do I have to do to make you understand?

On Mon, Aug 26, 2019 at 7:28 PM Ron S. <rohnski@hotmail.com<mailto:rohnski@hotmail.com>> wrote:
That is not what I'm talking about.  If you had bothered to look at the page you would see that it is essentially blank.

I've screen cap'd it.  What I was asking for was to include the stuff highlighted in yellow as hyperlinked text in the body of the page.  I like to copy stuff like that into my personal notes so I when I'm searching for help/tips, I know what is on the page without having to go to it every time.

And the same for each of the header pages.

[zzz.png]

On Mon, Aug 26, 2019 at 6:57 PM Simonx Xu <notifications@github.com<mailto:notifications@github.com>> wrote:

Every article in the TOC has the applied products displayed on the top of the page.

**Comment by jlriesco** [comment] 2020-03-13 23:11
Sorry but we can't see the screenshots or the highlighted text. Perhaps you could copy them to a Word document and then attach it to the comments?
Thanks.

**Comment by Reeced40** [comment] 2021-06-08 10:26
@Ronsss thank you for reaching out and helping improve MS Docs. I'm looking into this issue. I see the article was updated in May this year. Please let me know if you think anything still needs to be changed in the article. The TOC you are referring to - is that the "Access, Activation" etc.?? The articles are structured this way to make it user friendly. If you click on the relevant link on the left of the article it will take you directly to the related information with more dropdowns from there. Please let me know if you need any further help.

**Comment by Ronsss** [comment] 2021-06-08 14:07
<snip>
The TOC you are referring to - is that the "Access, Activation" etc.??
</snip>
Yes that is the part I was referring to.
I would like to be able to select it and copy it. But the way it is defined
on the page does not allow that to be done.

When I find useful web pages, I keep the link to the page as well as some
summary information to remind me of the future relevance of the page and
the date published/updated.  When I'm capturing the summary information
I'll often just copy the "summary" or "abstract" or introductory paragraph
along with major sub headings on the page.  On this page I wanted to
capture the list of applications covered as "sub headings". I understand it
is dynamic, but even a partial old list would help.

**Comment by Reeced40** [comment] 2021-06-10 10:21
@Ronsss thank you for giving more clarity. For now that is how the Docs are structured so as to ensure that each article relates to each topic, but we always take users feedback for future use to improve on MS Docs for user friendliness. Thank you for this. However, if you open an Excel Spreadsheet and under each heading on this article, eg. Access, all the sub headings eg .LDB files,  can be dragged and dropped into an Excel spreadsheet for easy access that can be saved for future use, if that would help at all? I've just tested it and it works well. Let me know if you need any further assistance.

**Comment by Ronsss** [comment] 2021-06-10 14:03
thanks for the tip about dragging links (it also works dragging to Word). I
recall seeing the paperclip icon in the past. I never tried it.
.
But the implementation of this feature is flawed. It only applies to sub
topics, ie, if I expand "Access" on the I can only drag the sub topics
under it. That is nice for creating links to specific topics, but I really
want to be able to drag the link to each whole topic, ie "Acess" to create
links to more generic help.

You can close this issue.

Thanks.

**Comment by Reeced40** [comment] 2021-06-11 08:11
Thanks for clearing that up @Ronsss and for your valuable input. I will bring this to the teams attention to look at for the future when continuously improving on MS Docs. @nam31 you can close this thank you.

**Comment by nam31** [comment] 2021-06-14 07:49
@Ronsss Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Also to make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).
Thank you

**Closed by nam31** 2021-06-14 07:49 UTC
Labels: CI created
