### ISSUE TITLE
Unable to Add Planner to Teams as Owner 

### ISSUE THREAD

**Issue by sambitsahugithub** [MicrosoftDocs/OfficeDocs-Support#697] opened 2020-07-30 06:36 UTC
[Enter feedback here]

The issue seems to be not recurring now as we found while adding a owner to teh teams the owner gets added to the member group as well of the associated Office 365 Group. Can you please confirm is this issue has been fixed or not for all new and existing tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3bb136-1d1b-5e1b-2e7a-d0862b0e19c6
* Version Independent ID: 8afb2dc3-bcf0-adc1-0af5-da16b886ccc1
* Content: [Teams owner unable to create a Planner tab - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-owner-cannot-create-planner-tab)
* Content Source: [Teams/known-issues/teams-owner-cannot-create-planner-tab.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/teams-owner-cannot-create-planner-tab.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **Colin.Witkowski**

**Comment by TobyTu** [comment] 2020-07-30 07:46
Thanks for your feedback, if the issue is fixed in your tenant, the issue should also be fixed in other tenants.

**Closed by TobyTu** 2020-07-30 07:46 UTC
