### ISSUE TITLE
Session TimeOut warning in OneNote Web and Excel WebApp

### ISSUE THREAD

**Issue by IstvanYbema** [MicrosoftDocs/OfficeDocs-Support#492] opened 2020-04-24 19:14 UTC
Would be a good thing to note that this also happens on OneNote Web Excel Webapps. Actually the user would already get a message that the session is about to expire; "Session will expire on". This message already is displayed after 5 min! Forcing the user to refresh the browser every 5. minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e90026b-1347-0e64-059c-e76a2d71830d
* Version Independent ID: 3945f762-b924-b40e-473a-817cea7c19b3
* Content: [Your session has expired in Office Online - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/your-session-has-expired-error#feedback)
* Content Source: [Microsoft365/admin/access-management/your-session-has-expired-error.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/your-session-has-expired-error.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment] 2020-05-08 13:29
@IstvanYbema. Check the settings in group policy Editor and in registry keys, if you or users made changes.

**Comment by IstvanYbema** [comment] 2020-05-08 14:45
Hi Raju, 
this is not group policy or registry related. I have already spent several hours with MS support engineer on this issue. It is a side effect on the ip-filtering settings. So my suggestion is to add this to the documentation.

**Comment by sowjanya365** [comment] 2021-06-01 07:05
Hi @IstvanYbema 

We see this issue due to the system time, date, or time zone on the affected computer. To resolve this issue, correct the system time, system date, or time zone.

Thank you!

**Comment by IstvanYbema** [comment] 2021-06-01 18:23
Hi Sowjanya365; what exactly do you mean by correcting the system time/date or time zone? It happend on multiple pc's inside and outside the customers network. The systems were all in sync with the correct time.

**Comment by sowjanya365** [comment] 2021-06-05 05:49
Hi @IstvanYbema 

Would you be so kind to elaborate more on the fix that resolved the issue. We will request the document owner to review it and consider for updating the document. Thank you!

**Comment by IstvanYbema** [comment] 2021-06-05 12:09
Hi @sowjanya365 ;
I tested the issue once again; since it has been a while since I created the comment. It happened as explained only in the webbrowsers apps when the IP Block feature was active. Now I tested it again in the same enviroments where it occured, but I can't reproduce it anymore. It looks like the issue has been resolved allready. Maybe the new Edge browser?

**Comment by sowjanya365** [comment] 2021-06-12 06:28
Hi @IstvanYbema 
We were also not able to reproduce it on our end! Feel free to let us know if you observe it again! Thank you for your contribution.

**Comment by nam31** [comment] 2021-06-18 13:49
@IstvanYbema We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-06-18 13:49 UTC
Labels: CI created
