### ISSUE TITLE
link at bottom of page does not work

### ISSUE THREAD

**Issue by mariajavier1** [MicrosoftDocs/OfficeDocs-Support#670] opened 2020-07-16 14:20 UTC
link at the bottom of the page does not work:  "Go to the [Office 365 service health dashboard page](https://portal.office.com/ServiceStatus/ServiceStatus.aspx) (admin sign in required), and check the status of the services under Exchange Online."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9133487-2048-dfe2-0f81-29c42d551ed7
* Version Independent ID: 9a37d778-c405-a2d9-e27d-d2f9eb049a03
* Content: [Fix Outlook connection problems in Office 365 and Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-connectivity/outlook-connection-issues)
* Content Source: [Exchange/ExchangeOnline/outlook-connectivity/outlook-connection-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-connectivity/outlook-connection-issues.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment] 2020-07-17 02:07
Thanks for your comment. What issue did you encounter? If you receive an error that says "You don’t have permission to access this page or perform this action", it means that you do not have the admin permission to perform the action.

**Comment by mariajavier1** [comment] 2020-07-17 12:56
[cid:dd66fe86-15f3-49ad-b265-68a4c8583b7d]

________________________________

**Comment by mariajavier1** [comment] 2020-07-17 12:58
You can try refreshing the page to solve the problem. You can also wait a few minutes and try again.
--
  | If the problem doesn't go away, please submit a Service Request.
  | CloseSupport InformationCorrelation ID:eus#d0eced53-938a-4a1d-b379-248c41e2d644Error code:0 |   | Correlation ID:eus#d0eced53-938a-4a1d-b379-248c41e2d644 |   | Error code:0
  | Correlation ID:eus#d0eced53-938a-4a1d-b379-248c41e2d644
  | Error code:0

**Comment by RAJU2529** [comment] 2020-07-18 19:27
@mariajavier1 .  that link does not with Microsoft's personal account.  You must sign in with an **organization email address** or **work email address**.

**Comment by mariajavier1** [comment] 2020-07-19 16:31
Yes I do not have a personal account. I am only signed in with my work account. It does not work.

**Comment by MaratMussabekov** [comment] 2021-06-10 05:54
Hello, if you cannot open the link, it means that your account doesn't have permissions to open this admin panel.
the link is completely fine, and works correctly.
Thank you

**Comment by mariajavier1** [comment] 2021-06-10 13:04
@RAJU2529  and @MaratMussabekov 
I am signed in with my work account and I AM the global admin. I merely was trying to relay that the documentation needed to be fixed, but it's not a big deal. Over one year later.

**Comment by MaratMussabekov** [comment] 2021-06-22 14:33
Hello @mariajavier1 ,
sure, there could be some problem with the link when you created the issue, however, currently it works fine. Wouldn't you mind if @nam31 close this issue?
Thank you

**Comment by nam31** [comment] 2021-06-24 14:54
@mariajavier1 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-06-24 14:54 UTC
