### ISSUE TITLE
KB 3178906 on SurfaceX (ARM processor)

### ISSUE THREAD

**Issue by bjarnegram** [MicrosoftDocs/OfficeDocs-Support#774] opened 2020-09-08 08:32 UTC
On my Microsoft Surface Pro X (ARM Processor) this workaround doesn't work.
Either this should be stated on the page, or a relevant workaround should be listed.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 338ba1fd-f650-af80-970a-eae802ec5368
* Version Independent ID: 061e81e5-6297-18f8-bacd-57053e44023f
* Content: [iCloud crashes when synchronizing data - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/icloud-crashes-sync-data)
* Content Source: [Outlook/Client/user-interface/icloud-crashes-sync-data.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/icloud-crashes-sync-data.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by msbemba** [comment] 2021-06-01 23:13
@bjarnegram Thank you for your feedback. Sorry about the delay in contacting you. This issue/bug was fixed in the subsequent update in November 2020. Could you please confirm if this is resolved? 

Thanks
Sri

**Comment by bjarnegram** [comment] 2021-06-02 13:42
Hi!
What exactly was fixed?
That the workaround works?
Which basically gives Outlook from 2016...
Or is the issue with iCloud on ARM actually fixed?
Because I tried updating Office and reinstalling iCloud, and that certainly doesn't work.
And reverting to an Outlook version from 2016 isn't an option.
I'm on Outlook: 16.0.14026.20254

**Comment by msbemba** [comment] 2021-06-02 15:18
@bjarnegram Thank you for your feedback. I meant the workaround.  If you revert to version 16.0.6868.2067, you can configure iCloud to synchronize Contacts, Calendars and Tasks with Outlook 2016 successfully. At this point, if you prefer to, you can update Office 2016 to the latest version or to 16.0.14026.20254 as long as you do not change the iCloud synchronization with Outlook.

Thanks
Sri

**Comment by msbemba** [comment] 2021-06-10 16:18
@bjarnegram Hope the above explanation helps. Let us know if you still think any documentation update is required.

Thanks
Sri

**Comment by nam31** [comment] 2021-06-14 08:26
@bjarnegram Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-06-14 08:26 UTC
Labels: CI created
