### ISSUE TITLE
Date calculation for year 1900

### ISSUE THREAD

**Issue by RAVCounsulting** [MicrosoftDocs/OfficeDocs-Support#1073] opened 2021-02-01 21:10 UTC
Excel stores dates as sequential serial numbers beginning with 1 as January 1, 1900.  Serial number 60 is shown as February 29, 1900, however, 1900 was not a leap year and there was no February 29th.  This has little effect unless you are doing date calculation that would include 2/29/1900.

The fix is also simple.  Update date display formula to account for 1900 as a non-leap year and change 1/1/1900 to serial number 0.  Or have serial number 1 represent 1/2/1900. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f92333-a9f0-7616-64e8-5aaceb1e3f40
* Version Independent ID: c8136395-44ec-6eb6-3153-53527baf19b3
* Content: [Method to determine whether a year is a leap year - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year)
* Content Source: [Office/Client/excel/determine-a-leap-year.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/determine-a-leap-year.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by PeterPesch** [comment] 2021-02-02 08:58
I always though that was behaviour by design, from the previous century ...
To make the original excel program behave just like the (at that time) leading spreadsheet program (probably Lotus 1-2-3)

**Comment by RAVCounsulting** [comment] 2021-02-02 17:19
Back then memory was a big issue as well sophistication of the software.  

 

The problem is mostly academic.  I guess the biggest issue is loss of confidence – If Excel can’t handle leap centuries correctly, what else doesn’t it do correctly?

 

Every program has bugs, but this one has been around for over 40 years!

 

Sincerely,

Roger A. Vernon

RAV Consulting

2625 Ginger Woods Dr.

Phone: 630-229-0786

Mobile: 630-460-7193

**Comment by PeterPesch** [comment] 2021-02-02 17:47
But if they would repair this, excel would no longer comply with the official standards for Open Office XML File Formats ...

**Comment by dariomws** [comment] 2021-07-01 15:12
Hi @RAVCounsulting, thank you for your feedback.

The article seems to be correct. Do you want to suggest an improvement?

**Comment by nam31** [comment] 2021-07-09 09:56
@RAVCounsulting We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-07-09 09:56 UTC
Labels: CI created

**Comment by RAVCounsulting** [comment] 2021-07-10 01:17
Already replied via text.Sent via the Samsung Galaxy Tab E, an AT&T 4G LTE tablet
-------- Original message --------From: nam31 ***@***.***> Date: 7/9/21  4:56 AM  (GMT-06:00) To: MicrosoftDocs/OfficeDocs-Support ***@***.***> Cc: RAVCounsulting ***@***.***>, Mention ***@***.***> Subject: Re: [MicrosoftDocs/OfficeDocs-Support] Date calculation for year 1900
  (#1073) 
@RAVCounsulting We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1073#issuecomment-877065789",
"url": "https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1073#issuecomment-877065789",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
