### ISSUE TITLE
Workaround Causes Blue Screen

### ISSUE THREAD

**Issue by eminsenay** [MicrosoftDocs/OfficeDocs-Support#860] opened 2020-10-20 10:03 UTC
Workaround #1 explained in this page caused a blue screen during restart. I was unable to login because of this and had to use system restore to continue working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd107c3b-1087-0241-0795-7afc59aea186
* Version Independent ID: 7abee709-caa5-e6fa-f8a3-c9c0603daace
* Content: [Can't send or receive email and Metered Connection Warning is triggered - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/profiles-and-accounts/metered-connection-warning)
* Content Source: [Outlook/Client/profiles-and-accounts/metered-connection-warning.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/profiles-and-accounts/metered-connection-warning.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment] 2021-06-20 03:58
@eminsenay Thank you for your feedback. Sorry about the delay, Did you receive the blue screen error after running the repair tool or was it after making the registry changes?

Thanks
Sri

**Comment by eminsenay** [comment] 2021-06-21 20:44
@msbemba No problem. I wasn't actually expecting for a return. It was a long time ago, indeed; so I'm not 100% sure if everything below is accurate:

I made the registry changes; however removal of the keys was unfortunately unsuccessful. Some of the keys remained there. Still Windows was functioning properly. I got the blue screen error after running the repair tool. But I'm not really sure if it is the repair tool's fault. I think some of my applications that start on startup were relying on these keys and removal of them started to cause blue screens on startup.

**Comment by msbemba** [comment] 2021-06-22 00:31
@eminsenay Thank you for the quick response. I was able to test it on a test machine and it did not trigger any such issues. However, your case could be different. If you have a similar issue, please let us know so we can investigate and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-09 11:02
@eminsenay Thank you for your feedback. We will proceed to close this issue, In case you'd like to see a change in the document please open a new issue.

@nam31 There are no changes required in the document.

Thanks
Sri

**Comment by nam31** [comment] 2021-07-13 11:07
@eminsenay Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-13 11:07 UTC
Labels: CI created
