### ISSUE TITLE
This also occurs when attempting to swap an email address.

### ISSUE THREAD

**Issue by aforgettableaccount** [MicrosoftDocs/OfficeDocs-Support#46] opened 2019-07-18 19:20 UTC
This error "Proxy address is already being used"  "Please choose another proxy address" 
also occurs when trying to swap an email address to another object. There is a non-obvious lengthy time (an hour?) after removing an address from an account, preventing it from being re-assigned to another account.  Any chance of a powershell move address command, so we don't have to sit around guessing while mail bounces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2473020-afb3-5811-8119-1b102c342a20
* Version Independent ID: 8f5ea090-348a-04ea-90fd-da478d27d8a2
* Content: [Proxy address is already being used](https://docs.microsoft.com/en-us/exchange/troubleshoot/add-users/proxy-address-being-used)
* Content Source: [Exchange/ExchangeOnline/add-users/proxy-address-being-used.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/add-users/proxy-address-being-used.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Weychris** [comment] 2019-11-08 15:07
still an issue.

**Comment by MaratMussabekov** [comment] 2021-06-10 03:07
Hello @aforgettableaccount ,
**There is a non-obvious lengthy time (an hour?) after removing an address from an account, preventing it from being re-assigned to another account.** - yes, it is expected since the mailboxes are located in several locations (for redundancy purpose), some time for replication is required
**Any chance of a powershell move address command, so we don't have to sit around guessing while mail bounces?** - there is no such command (at least yet)
Thank you

**Comment by nam31** [comment] 2021-06-14 07:17
@aforgettableaccount Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-06-14 07:17 UTC
Labels: CI created
