### ISSUE TITLE
Microsoft Outlook crashing upon startup after new software July 15, 2020

### ISSUE THREAD

**Issue by drquine** [MicrosoftDocs/OfficeDocs-Support#666] opened 2020-07-15 16:11 UTC
Recommended registry edit did not help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3e1325-8447-d157-729e-f668bef41db0
* Version Independent ID: f411b63a-8be9-9ac4-3f1c-8746216d243d
* Content: [Office Applications crash or cannot start - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/office-crash-or-cannot-start)
* Content Source: [Microsoft365/enterprise/administration/office-crash-or-cannot-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/administration/office-crash-or-cannot-start.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment] 2021-07-09 10:56
@drquine Thank you for your feedback. This document pertains only to office 2016. If you are using the same version, Could you confirm if the latest update fixed the issue?

Thanks
Sri

**Comment by drquine** [comment] 2021-07-09 21:50
Sri,

This problem was reported a YEAR ago. It was resolved at the time with further new versions of the software. If it had taken a year to resolve I would have moved to a new vendor months ago. I do wish that Microsoft could release STABLE software. Almost every week’s patch introduces new instabilities to manage.

Best regards, Doug

Sent from my iPhone

On Jul 9, 2021, at 6:56 AM, Sriraman M S ***@***.***> wrote:

﻿
@drquine Thank you for your feedback. This document pertains only to office 2016. If you are using the same version, Could you confirm if the latest update fixed the issue?

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-11 18:33
@drquine Thank you for your feedback. Microsoft strives hard to fix existing Bugs via updates. We value your feedback and will pass this on to the team.

Have a nice day!

@nam31 Please close the issue.

Thanks
Sri

**Comment by nam31** [comment] 2021-07-14 18:31
@drquine Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-14 18:31 UTC
Labels: CI created
