### ISSUE TITLE
EWS - Modern Authentication

### ISSUE THREAD

**Issue by reevesjeremy** [MicrosoftDocs/OfficeDocs-Support#1399] opened 2021-05-17 21:15 UTC
This script only uses Basic Authentication which is going away in the unknown future. Please provide an EWS Modern Auth method.

**Comment by nam31** [comment] 2021-05-18 06:24
@reevesjeremy The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by reevesjeremy** [comment] 2021-05-19 00:56
https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/personmetadata-items

**Comment by msbemba** [comment] 2021-06-22 19:00
@reevesjeremy Thank you for your feedback. There is currently no Modern auth method available. Once we have steps to do the same with EWS modern auth, the document will be updated. 

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-09 11:00
@nam31 This issue can be closed as there is no Modern auth method available currently.

Thanks
Sri

**Comment by nam31** [comment] 2021-07-13 11:06
@reevesjeremy Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-13 11:06 UTC
