### ISSUE TITLE
Tried a lot of solutions when suddenly this blank message body problem occured to my Outlook - finally found a resolution when I corrected a corrupted password in my iphone - as soon as sync occured all the Outlook issues resolved.

### ISSUE THREAD

**Issue by GitHubJohn2** [MicrosoftDocs/OfficeDocs-Support#1366] opened 2021-05-12 22:08 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6235ea9-d8df-c7c8-5540-402bbf2bf459
* Version Independent ID: 887b3e23-dd0b-caa8-0a20-3f754fc9bb86
* Content: [Email message body is blank in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/email-message-body-is-blank-in-outlook)
* Content Source: [Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/message-body/email-message-body-is-blank-in-outlook.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment] 2021-06-14 21:21
@GitHubJohn2 Thank you for your feedback. The emails going blank issue was more related to a service incident and should be fixed now. The issue was caused by an update and was fixed later in the same day.

Let us know if the issue persists.

Thanks
Sri

**Comment by nam31** [comment] 2021-06-22 18:43
@GitHubJohn2 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed** 2021-06-23 16:20 UTC
