### ISSUE TITLE
Link to download SaRa Network Tool is dead

### ISSUE THREAD

**Issue by twist3dimages** [MicrosoftDocs/OfficeDocs-Support#1760] opened 2021-08-24 16:39 UTC
Link to download SaRa Network Tool is dead. Says it  can't find the file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bdf1bb1-b24c-ffb7-3939-dde9dc0a1191
* Version Independent ID: 2e0f5d9e-8c9f-121c-17c0-b1157cebdebb
* Content: [Install and maintain SaRA tool from a network share - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/install-sara-from-network-share)
* Content Source: [Microsoft365/admin/installation/install-sara-from-network-share.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/installation/install-sara-from-network-share.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nutterthanos** [comment] 2021-08-29 02:51
maybe the file got updated?

**Comment by nutterthanos** [comment] 2021-09-01 00:01
nvm link works again @twist3dimages

**Comment by nutterthanos** [comment] 2021-09-02 10:29
@nam31 this can get closed

**Comment by nam31** [comment] 2021-09-02 13:53
@twist3dimages It seems that the question has been answered by the community, and thus the issue is being marked as resolved.

**Closed by nam31** 2021-09-02 13:53 UTC
Labels: doc-bug
