### ISSUE TITLE
Merge Function Leaves Much to Be Desired

### ISSUE THREAD

**Issue by PatriotOGrady** [MicrosoftDocs/OfficeDocs-Support#472] opened 2020-04-20 00:27 UTC
Word's "merge" function is a disaster.  The point of merging is to work with small documents that can be merged after the fact because Word is TOO SLOW when working with documents above 10 MB.  I have a 200,000-word document that I have broken up into 20 or so chapters.  Unfortunately, Word's merge function is extremely sloppy at preserving formatting, pagination, colors, fields, and underlines, etc. etc.  In other words, the merge function is basically useless for its design intent.  Quality products like Adobe's Acrobat have no problem merging 20 or more documents and preserving every bit of formatting.  Get your act together Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25557df-12d9-2b76-eba2-a3c8134d294a
* Version Independent ID: c8a4f4fd-dbbe-0c41-5c4a-0dd10f7caa93
* Content: [How to merge multiple Word documents into one - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/merge-word-documents#feedback)
* Content Source: [Office/Client/word/merge-word-documents.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/merge-word-documents.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Melanie-Rimmer** [comment] 2020-05-09 17:42
Agreed. I tried to merge 5 one-page documents with several frames in each. Each one looked perfect on its own, but after merging the formatting went completely haywire. Not only were the frames in the wrong places, but the fonts, font sizes etc within the frames was changed completely. Absolute pants.

**Comment by Reeced40** [comment] 2021-07-01 11:31
@LEONARDODC71 thank you for reaching out and helping to improve MS Docs. Please let me know if you're still having this issue.  I've just tried the merge function on a few small documents and it is working my side. I found that wherever your cursor is placed, the documents will be added above that. Also see the note:  Note - Documents will be merged in the order in which they appear in the file list. To use a different order, select and insert each file individually in the desired order. Please let me know if there is anything else I'm missing or can help with.

**Comment by Reeced40** [comment] 2021-07-12 12:22
@LEONARDODC71 please can you let me know if this has been resolved or if you need further assistance. Thanks.

**Comment by nam31** [comment] 2021-07-26 13:24
Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-26 13:24 UTC
Labels: CI created
