### ISSUE TITLE
What's the actual cause for something that we can't change without downloading an extra tool?

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/OfficeDocs-Support#1691] opened 2021-07-16 22:42 UTC
The way this article is written, the cause of folders disappearing is that the hidden attribute is set to True.

But there is no suggestion of what could suddenly cause this attribute to be changing to True for users.
If we have to download an MFCMAPI tool to fix this issue, it indicates that it's unlikely for us to be able to accidentally hide the folders in some way, meaning it would be some kind of back end issue with MS/Outlook causing these attributes to suddenly change, but then we have to fix manually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d44945-98d8-e545-80ee-7f3ecca5d074
* Version Independent ID: 8de21a8e-75e3-0bab-9ecb-090e23841eee
* Content: [Default folder is missing - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/user-interface/default-folder-is-missing)
* Content Source: [Outlook/Client/user-interface/default-folder-is-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/user-interface/default-folder-is-missing.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment] 2021-07-24 17:25
Hello @Krytical13 ,
**But there is no suggestion of what could suddenly cause this attribute to be changing to True for users.** - there could be various reasons why some attribute of the mailbox was changed - updates, third-party applications, add-ins, bugs in Exchange server or in MS Outlook
**but then we have to fix manually?** - no built-in tool allows to change this kind of attributes, so it could be fixed only manually  using MFCMAPI.

Thank you

**Comment by nam31** [comment] 2021-07-29 16:37
@Krytical13 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-29 16:37 UTC
