### ISSUE TITLE
Office 365 group shared inbox

### ISSUE THREAD

**Issue by jmountforduk** [MicrosoftDocs/OfficeDocs-Support#301] opened 2020-01-09 09:45 UTC
Is there a reason why the email isn't also delivered to the shared inbox of the Office 365 group? This happens with emails from Planner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5837d9-04a2-ffb7-19f4-1b6538cd7630
* Version Independent ID: 97de6157-49d3-99e6-91a5-6d669b95cd90
* Content: [No email notifications for responses to Group Forms - Office](https://docs.microsoft.com/en-us/office/troubleshoot/microsoft-forms/no-email-notifications-for-responses-to-group-forms#feedback)
* Content Source: [Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/microsoft-forms/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by JakeDWarren** [comment] 2020-02-14 14:41
I agree. Is there any more info on why we don't see it in the group mailbox.

**Comment by VLG17** [comment] 2021-06-07 17:31
@jmountforduk Planner mail notifications need to be turned on for the group assigned to the Plan. More details [here](https://support.microsoft.com/en-us/office/manage-planner-notifications-f6a32f83-058d-4f39-988d-8a2e932820ec).

> If you've created a plan in Planner, then you are the group owner for the plan. The group owner can change a plan setting that will send group email messages to the group when a task is assigned or completed. **By default, the group emails will not be sent to the plan's group mailbox in Outlook**. If a member chooses to follow the group, then these activity emails will go to the plan member's inbox.

**Comment by nam31** [comment] 2021-06-11 17:48
@jmountforduk Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-06-11 17:48 UTC
Labels: CI created
