### ISSUE TITLE
this did not clear the error message

### ISSUE THREAD

**Issue by Tprestegaard** [MicrosoftDocs/OfficeDocs-Support#712] opened 2020-08-06 17:05 UTC
My user is getting a error message on opening Word and Outlook.  the Compatibility tab was not in properties.  Running the Troubleshooting compatibility did not resolve the problem.
Prior to trying this document I updated windows and rebooted.  I (change)repaired Office 2016 from the control panel.  rebooted again.  

Our organization is running Windows 10 1803 64 bit and Office 2016 64 bit.  I have issues with the feature update 1903, in this case the Symbol hand barcode scanner stopped working.  I upgraded to w10 2004 which has solved this issue in the past and it solved the barcode scanner issue (with a reset of the hardware) while  the Fi-7160 scanner application was removed and not replaced I fixed that with Windows store Windows Scan- and inferior product but the user was happy to be able to scan again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dfca234-859d-b43d-5868-a61f709b1947
* Version Independent ID: 794772a8-2dd5-9ff3-ccd0-4c22e06e144d
* Content: [Cannot verify the license for this product when start an Office app - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/license-issue-when-start-office-application)
* Content Source: [Office/Client/activation/license-issue-when-start-office-application.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation/license-issue-when-start-office-application.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment] 2020-08-07 02:15
Thanks for your comments. We are glad to hear that the issue is resolved by the Windows update. Your scenario is useful.

**Closed by simonxjx** 2020-08-07 02:15 UTC

**Comment by xsisbest** [comment] 2020-08-07 16:40
These solutions do not work for me either. The only way to get this error to go away for me is do an in place Windows install of the current build which in my case is Windows 10 build 2004. It seems that version 2004 is breaking our office activation and no matter what you do you cannot fix it. There is no compatibility tab and reactivating causes the message to say there was a problem with the installation and needs to quit. Then you can't even use Word at all after that. 
An in place upgrade just reinstalls the current build and keeps all your files so there is no loss but time. In an hour you will be back to normal and it will activate. Just Google Windows 10 2004 iso download. Download the ISO, extrac the contents to your desktop or to a folder of your choice and run setup.exe.. follow the directions and install.

**Comment by Tprestegaard** [comment] 2020-08-07 17:57
This is an open issue

**Comment by Tprestegaard** [comment] 2020-08-07 18:02
You misread it.  Windows is still very broken.  The 1903 update Broke the symbol scanner (for a Town Clerk scanning mail in votes).  The 2004 update broke a desktop scanner and created an error that office could not reach licensing server.  The UPDATES BROKE EVERYTHING AND FIXED NOTHING.

Also the suggestion to use “SetupProd_OffScrub” does not uninstall office 2016 and seems to have permanently damaged windows so it could not run the setup for Office 2016.
