### ISSUE TITLE
privacy list error when troubleshooting spotlight issues

### ISSUE THREAD

**Issue by ajRiverav** [MicrosoftDocs/OfficeDocs-Support#82] opened 2019-08-09 20:07 UTC
As a result to following the troubleshooting steps in https://support.microsoft.com/en-us/help/2741535/outlook-for-mac-search-returns-no-results-and-task-items-are-not-displ, I get ![image](https://user-images.githubusercontent.com/22076301/62805997-930af700-babf-11e9-9a3f-f82ee7f29c4b.png) when I try to add the specified folder.

**Comment by msbemba** [comment] 2021-06-20 03:47
@ajRiverav Thank you for your feedback. The error relates to the privacy list on the mac machine and is usually resolved by deleting the file - .Spotlight-V100/Store-V1/Exclusions.plist. This is more of an apple error, let us know if this still persists.

Thanks
Sri

**Comment by nam31** [comment] 2021-06-23 16:22
@ajRiverav Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-06-23 16:22 UTC
