### ISSUE TITLE
I think there is a mistake?

### ISSUE THREAD

**Issue by Kirill-PCPORT** [MicrosoftDocs/OfficeDocs-Support#261] opened 2019-12-11 13:41 UTC
Synchronized identity model
...r $_.SAMAccountName –replace @{PreferredLanguage="it-it"}}
There should be ...@{'PreferredLanguage'="it-it"}} ? At least it did work for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca598276-1e7e-4105-81c4-45b2b9f0ba52
* Version Independent ID: e22af2fd-1e50-6c16-2377-fa00a91f68f3
* Content: [Set language and region settings for Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/set-language-and-region#feedback)
* Content Source: [Microsoft365/admin/administration/set-language-and-region.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/set-language-and-region.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by sowjanya365** [comment] 2021-07-07 12:00
Hi @Kirill-PCPORT 

Thank for your contribution.

We have checked this within the team. And we have received the following response. 

"Single quote isn't needed for AttributeLDAPDisplayName, see example in https://docs.microsoft.com/en-us/powershell/module/activedirectory/set-aduser?view=windowsserver2019-ps "

Hope this clarifies your query! 

We are closing this issue! Please do let us know if you have any questions. Thank you once again!

**Comment by nam31** [comment] 2021-07-26 13:16
Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-26 13:16 UTC
Labels: CI created
