### ISSUE TITLE
Basic Authorization failed

### ISSUE THREAD

**Issue by akvadlamani** [MicrosoftDocs/OfficeDocs-Support#436] opened 2020-04-02 13:48 UTC
I assigned the user has all admin permissions but still get the following error. 

PS /home/chris&gt; $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
New-PSSession: [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : Basic Authorization failed for user xxxxx@xxxxxxx.onmicrosoft.com For more information, see the about_Remote_Troubleshooting Help topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7466a6-9557-8c01-02c2-516732c3c17f
* Version Independent ID: 7d82a28b-6229-7d2b-dc4e-b7a793f4c649
* Content: [Access is denied when you connect to Exchange Online with Windows PowerShell - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/connecting-to-the-service/access-denied-connect-powershell#feedback)
* Content Source: [Exchange/ExchangeOnline/connecting-to-the-service/access-denied-connect-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/connecting-to-the-service/access-denied-connect-powershell.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by githubpama** [comment] 2020-04-20 20:15
facing the same issue when trying to connect:
PS C:\Users\pama> Connect-EXOPSSession -UserPrincipalName patrick@o365pr.onmicrosoft.com -ConnectionUri https://outlook.office365.us/powershell-liveid -AzureADAuthorizationEndPointUri https://login.microsoftonline.us/common
New-ExoPSSession : Connecting to remote server outlook.office365.us failed with the following error message : Access
is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Users\pama\AppData\Local\Apps\2.0\D41KZOTD.4OO\PXCON0HM.JO8\micr..tion_45baf49ae30bdb15_0010.0000_9957e8953b5cb90
3\CreateExoPSSession.ps1:302 char:30
+ ... PSSession = New-ExoPSSession -UserPrincipalName $UserPrincipalName.Va ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

**Comment by daverickdunn** [comment] 2020-04-24 11:58
Same issue on a new tenant created 4 days ago. We've been running the same scripts (programatically) on test tenants for almost a year now without any changes to the program/scripts, the only difference is that they've all been E5's. Since I can find no other reason for this to be happening, I'm going to create a new E5 and test again. Licensing aside, could be a new bug, with new tenants?

**Comment by daverickdunn** [comment] 2020-04-24 12:13
Found a difference, and it resolved my issue. I did detailed comparisons of Azure, Msol, Azure Users and Msol Users via PowerShell and could not spot this. Finally found it in the Azure website under: 

Azure Admin Centre > Azure Active Directory > Properties > Manage Security defaults > Enable Security defaults.

Toggling that off allowed me to login to EXO. 

This appears to be a macro to enable / disable numerous settings globally. Which setting was blocking access I do not yet know. I do know that MFA was not enabled. I suspect it might be "Modern Auth", but need to investigate this feature further.

**Comment by msbemba** [comment] 2021-05-27 20:46
@akvadlamani Thank you for your feedback. As rightly pointed about by @daverickdunn  This issue can occur when Security defaults is enabled. I have added the cause and recommendations to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1483

Thanks
Sri

**Comment by nam31** [comment] 2021-05-31 13:04
Closing via #1483
Thank you

**Closed by nam31** 2021-05-31 13:04 UTC
Labels: CI created
