### ISSUE TITLE
stay signed in option not available

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/OfficeDocs-Support#698] opened 2020-07-30 06:52 UTC
When using internet explorer to go to sharepoint online it logs me in automatically because the account on my computer is the same as for O365 so it says "logging in using windows". No option to select "Stay signed" is presented, even not after logging out manually.

Mapping the driver doesn't work.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Mapping and syncing network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment] 2020-07-31 01:44
Thanks for contacting Microsoft. I suggest that you can use InPrivate Browsing in Internet Explorer to make a try.

**Comment by VLG17** [comment] 2021-06-23 17:40
@valentijnscholten I'll start with the basic stuff, so did you try to delete cookies? Same thing?

Also, are you using ADFS with Windows Integrated Authentication? This behavior can be potentially caused by a wrong ADFS claim. Could you or the responsible person check that?

Looking forward to your feedback related to this issue.

**Comment by nam31** [comment] 2021-06-29 19:23
@valentijnscholten We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Closed by nam31** 2021-06-29 19:23 UTC
