### ISSUE TITLE
Skype for Business client

### ISSUE THREAD

**Issue by dan-git-s** [MicrosoftDocs/OfficeDocs-Support#331] opened 2020-01-28 13:04 UTC
Any advice on how this affects the Skype for Business client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by hpsin** [comment] 2020-01-29 23:44
Skype for Business found impacts and is working on a fix.  We will update when we have a firm date for the patch.

**Comment by TobieFysh** [comment] 2020-01-31 09:11
As "Microsoft is committed to addressing this change in behavior in its products and services before the February 4, 2020, rollout date." I guess there will be an update over the weekend? 

A link to a KB with what the impact will be if this is not patched would be good, and then that KB can be updated to reflect the availability of the patch once it is released!

**Comment by hpsin** [comment] 2020-02-04 18:48
We are updating the document now with the latest from our SfB team - 
The client is not impacted, but the server is, and will require an update.  They will be coming out in CU 3 and 11 (estimated March and April).  

SfB Server 2019 – March CU (CU 3)
SfB Server 2015 – April CU (CU 11)

**Comment by hpsin** [comment] 2020-02-04 18:48
#please-close as the team has provided dates for the article.

**Comment by TobieFysh** [comment] 2020-03-26 14:20
@hpsin - with CU3 for SfB2019 released can you confirm that this fix is included - I can't see anything in the release notes

**Comment by hpsin** [comment] 2020-03-28 02:11
Hey Tobie,

I confirmed with the team that it was fixed in cu3, just not documented. We're seeing about updating the release notes with a kb.

**Comment by TobieFysh** [comment] 2020-04-01 08:07
@hpsin - looks like it's not been fixed in CU 3 as the text above has changed to "Upcoming late Summer 2020 Cumulative Update (tentative)".... Any ideas?

**Comment by hpsin** [comment] 2020-04-01 17:10
Yes  the team checked and realized that it did not in fact make it into cu3, so they updated the text here. Thanks for catching this.

**Comment by TobieFysh** [comment] 2020-05-01 08:50
@hpsin - well here's the first of May and the CU for SfB 2015 isn't out.... Any update?

**Comment by TobieFysh** [comment] 2020-05-12 16:09
@hpsin - bump

**Comment by TobieFysh** [comment] 2020-05-13 16:12
Looks like the fix for this is now in SfB Server 2015..... And looks like only hitting UCMA applications? If we can have confirmation that would be good as the worry has been that this was a core part of the application and not for addon applications.

https://support.microsoft.com/en-us/help/4549672/

**Comment by MaratMussabekov** [comment] 2021-07-05 10:19
Hello @TobieFysh ,
please have a look at #1658 
Thank you

**Comment by nam31** [comment] 2021-07-09 06:42
Closing via #1658 
Thank you

**Closed by nam31** 2021-07-09 06:42 UTC
