### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by WerdnaP1980** [MicrosoftDocs/OfficeDocs-Support#1057] opened 2021-01-27 15:33 UTC
Dead Link for the compatibility checker:

https://www.microsoft.com/en-us/download/404Error.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9d72a7-fb83-a2ad-a554-14fa34dada8c
* Version Independent ID: a3aa12c6-f6aa-1cdc-82b9-93c2a232d173
* Content: [User not seeing add-ins - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/user-not-seeing-add-ins)
* Content Source: [Microsoft365/admin/access-management/user-not-seeing-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/access-management/user-not-seeing-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by RAJU2529** [comment] 2021-01-28 04:48
@WerdnaP1980 . Just now I checked article and I found deployment compatibility checker link is working.
use below link to download.
**https://www.microsoft.com/en-us/download/details.aspx?id=55270**

**Comment by WerdnaP1980** [comment] 2021-01-28 07:34
Thank you. I’ll recheck.

**Comment by nam31** [comment] 2021-05-26 10:04
@WerdnaP1980 It seems that the question has been answered by the community, and thus the issue is being marked as resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve. Thank you.

**Closed by nam31** 2021-05-26 10:04 UTC
