### ISSUE TITLE
Probable Typo - Cannot send emails to an external recipient

### ISSUE THREAD

**Issue by AaqibIqbal** [MicrosoftDocs/OfficeDocs-Support#1271] opened 2021-04-15 17:22 UTC
Please confirm if the below line is correct:
Exchange Online and Exchange Online Protection use multiple IP addresses to send mail. Because of DNS limitations, all these IP addresses CAN be mapped through the PTR record to the server name that's in the message HELO string.
Or should it be:
Exchange Online and Exchange Online Protection use multiple IP addresses to send mail. Because of DNS limitations, all these IP addresses CANNOT be mapped through the PTR record to the server name that's in the message HELO string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90df14e2-cbaf-3373-1531-a51534fa70a2
* Version Independent ID: 44f721a2-d7e4-5b9c-6c8c-b6568a739165
* Content: [Cannot send emails to an external recipient - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/antispam-and-protection/cannot-send-emails-to-external-recipients)
* Content Source: [Exchange/ExchangeOnline/antispam-and-protection/cannot-send-emails-to-external-recipients.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/antispam-and-protection/cannot-send-emails-to-external-recipients.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @Norman-sun
* Microsoft Alias: **v-swei**

**Comment by MaratMussabekov** [comment] 2021-05-14 04:50
Hello, 
fixed by https://github.com/MicrosoftDocs/OfficeDocs-Support/commit/2a635577d7f172779b27b984eed975b37792724e#diff-bffbef4e86d7ff2f2b343182da409259dca8f78027c2d7c5aa9c343df246d73b, and I believe it can be closed.
Thank you

**Comment by nam31** [comment] 2021-05-28 15:17
@AaqibIqbal Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-05-28 15:17 UTC
Labels: CI created
