### ISSUE TITLE
Users can't see free/busy information after a mailbox is moved to Office 365

### ISSUE THREAD

**Issue by JNDDaniel** [MicrosoftDocs/OfficeDocs-Support#594] opened 2020-06-09 04:51 UTC
Users can't see free/busy information after a mailbox is moved to Office 365. This seems to be the same issue i'm facing for one of my users that has been migrated last week.
However this article showing Default permissions is not available for the user, or myself, or other users that i have migrated. 
Where your article says Default and Anonymous, i can only see "My Organization" = Can view when I'm busy. Is that the same thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660e3bde-f546-4e40-033d-e29cdb40222f
* Version Independent ID: 565146bb-2414-80a6-8755-a00f752d410a
* Content: [Users can't see free/busy information after a mailbox is moved to Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/move-mailboxes/cannot-see-free-busy-information)
* Content Source: [Exchange/ExchangeOnline/move-mailboxes/cannot-see-free-busy-information.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/move-mailboxes/cannot-see-free-busy-information.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment] 2021-07-09 10:54
@JNDDaniel Thank you for your feedback. The Default Permissions is applied to all users within the organization. Whereas My organization could be a Security group within the organization for all users. If that is the case then both are the same.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-13 13:19
@JNDDaniel Just circling back to check to if you continue to have this issue or are we good to close the issue?

Thanks
Sri

**Comment by JNDDaniel** [comment] 2021-07-13 23:20
I no longer have an issue with the "doc.microsoft" page if that is what you are asking. But after 2-3 months of MS support there has been no solution to the actual technical problem I am experiencing.. just basically create a brand new user account and mailbox.

**Comment by nam31** [comment] 2021-07-14 18:30
@JNDDaniel Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-14 18:30 UTC
Labels: CI created
