### ISSUE TITLE
This also occurs with multiple domains

### ISSUE THREAD

**Issue by arminreiter** [MicrosoftDocs/OfficeDocs-Support#100] opened 2019-08-26 14:09 UTC
if there are multiple domains in the office365 tenant, the same error occurs for shared mailboxes with the same name.
if there is a shared mailbox "support@domainA.com" and you want to create another shared mailbox "support@domainB.com", the same error occurs. Thats really a big issue if you have multiple domains and you need different mailboxes for support, privacy or any other "general" address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2473020-afb3-5811-8119-1b102c342a20
* Version Independent ID: 8f5ea090-348a-04ea-90fd-da478d27d8a2
* Content: [Proxy address is already being used](https://docs.microsoft.com/en-us/exchange/troubleshoot/add-users/proxy-address-being-used#feedback)
* Content Source: [Exchange/ExchangeOnline/add-users/proxy-address-being-used.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/add-users/proxy-address-being-used.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by WanaGo** [comment] 2019-09-16 03:29
Exact same problem here. We have 3 domains, and I am trying to set up the shared inbox's and have the exact same problem, saying the alias is used. There must be a solution to this, surely!?

**Comment by Filimindji** [comment] 2019-09-25 08:59
I also have the issue but in my case, I have :

An alias called **contact@domainA.Com**
and I want to create a share mailbox  **contact@domainB.Com**

**Comment by WanaGo** [comment] 2019-09-25 09:07
This might help, the workaround which seems to work, but shouldnt be required.

https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/38606767-office365-multiple-domains-shared-mailboxes-wi

**Comment by Cloud-Horizon** [comment] 2020-01-17 01:57
It might be a bit fiddly but you can create a unique name and therefore a unique alias will be created by default. Set the unique alias as your primary shared mailbox account and then create an alias for the name you actually want. Once you've done that, make that alias your primary account and then delete the original unique name but keep the alias in place.

**Comment by WanaGo** [comment] 2020-01-17 04:46
> 
> 
> It might be a bit fiddly but you can create a unique name and therefore a unique alias will be created by default. Set the unique alias as your primary shared mailbox account and then create an alias for the name you actually want. Once you've done that, make that alias your primary account and then delete the original unique name but keep the alias in place.

Yep thats the work around I used.

**Comment by msbemba** [comment] 2021-05-28 19:27
@arminreiter Thank you for your feedback. I have updated a workaround to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1496

Thanks
Sri

**Comment by nam31** [comment] 2021-05-31 13:12
Closing via #1496 
Thank you

**Closed by nam31** 2021-05-31 13:12 UTC
Labels: CI created

**Comment by 4dsystems** [comment] 2021-05-31 20:35
Has this been solved, or is there only the same workaround in place still?

**Comment by msbemba** [comment] 2021-05-31 21:22
@4dsystems Yes, There is no resolution as it is by design that the proxy address alias@domain.onmicrosoft.com gets added to a user account. We have the workaround documented for now.

Thanks
Sri
