### ISSUE TITLE
fixing advice for firefox wildcard urls

### ISSUE THREAD

**Issue by AndyP2** [MicrosoftDocs/OfficeDocs-Support#1713] opened 2021-08-02 12:33 UTC
[Enter feedback here]
Mozilla Firefox does not accept cookie exception URLs like `https://*.microsoft.com`

The firefox support question [Wildcard not working in cookies exceptions](https://support.mozilla.org/en-US/questions/1134200) says you should remove the asterisk and put `https://microsoft.com`.

I have verified it works; you might like to update the document to say this for all 6 URLs instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment] 2021-08-05 14:55
@AndyP2 Thank you for your feedback. Firefox doesn't accept wildcards, so we need to add the complete email address which is not possible in this particular scenario ((i.e. 'Microsoft Teams is stuck in a login loop') as the URL's differ depending on the tenants. We have another workaround for this which is to disable enhanced tracking for websites, however that could pose other risks. I have removed the instructions via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1724 to avoid any confusion.

Thanks
Sri

**Comment by AndyP2** [comment] 2021-08-05 15:00
firefox does accept partial URLs though, which satisfies what that article is trying to achieve. There is no need to remove the firefox instructions as they only need a small tweak to be functional.
As I said before, I tested it and it works; I no longer get an infinite loop when trying to open teams in firefox.

**Comment by msbemba** [comment] 2021-08-05 15:04
@AndyP2 I could not reproduce the issue. However, I have made the changes to reflect the steps without wildcard and will wait for the author to review and approve.

PR# https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1724 has been updated.

Thanks
Sri

**Comment by nam31** [comment] 2021-08-06 10:27
Closing via #1724 
Thank you

**Closed by nam31** 2021-08-06 10:27 UTC
