### ISSUE TITLE
Default View in Word 2019

### ISSUE THREAD

**Issue by hubwoop** [MicrosoftDocs/OfficeDocs-Support#99] opened 2019-08-26 12:47 UTC
The steps described in this guide seem to be incorrect for Word 2019. The document still opens in Printlayout after setting "Allow opening a document in Draft view" and selecting draft view under "views".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3160fc5-6f2e-246b-1996-b2dcc239ff8d
* Version Independent ID: 8b94b374-3e69-c652-d7b3-72e0ccbbf1f5
* Content: [How to change the default view to Draft view in Word - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/change-default-view-to-draft-view#feedback)
* Content Source: [Office/Client/word/change-default-view-to-draft-view.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/change-default-view-to-draft-view.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment] 2019-10-24 16:13
The behavior is that Word saves the user’s choice of view selection on save. Current Win view behavior remembers the last view of the app, but only for Print, Read, and Web View Options However, for views like  "Draft" and "Outline" isn’t working due to a regression. This issue was recently addressed in Mac. For Windows, it's on the queue to be fixed.

**Closed** 2019-10-24 16:13 UTC
