### ISSUE TITLE
Steps for prevent this issue

### ISSUE THREAD

**Issue by ecanales88** [MicrosoftDocs/OfficeDocs-Support#1308] opened 2021-04-27 16:57 UTC
[Enter feedback here]
I would like to see what are the steps to avoid this issue. For example:
Disable the smtp-auth 
Transport rules
etc
This isssue is severety and we need to know how to avoid.
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4981be35-6e1f-cf1f-8fa9-de7c6359cb69
* Version Independent ID: cb91a17a-507c-ba36-7dc1-508f0c5dfa20
* Content: [Tenant has exceeded threshold NDR when mail is sent from your organization. - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/antispam/tenant-has-exceeded-threshold#cause)
* Content Source: [Microsoft365/security/antispam/tenant-has-exceeded-threshold.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/security/antispam/tenant-has-exceeded-threshold.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment] 2021-08-10 17:26
@ecanales88 Thank you for providing feedback to help improve a Microsoft product! 
We are going to close this issue as this limit has been included in the Cause section.

**Closed by nam31** 2021-08-10 17:26 UTC
