### ISSUE TITLE
This is not a resolution for the error xxxx@yyy.com hasn't been added to your organisation's directory. Contact your admin or try a different email.

### ISSUE THREAD

**Issue by ks2018ks** [MicrosoftDocs/OfficeDocs-Support#1037] opened 2021-01-21 12:36 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab509e31-52d3-be39-501a-aef6c701201c
* Version Independent ID: 4c2f3f40-91ca-7bb2-3090-6fd38ba82f40
* Content: [Someone has already set up Teams for your organization error in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/someone-has-already-setup-teams)
* Content Source: [Teams/teams-sign-in/someone-has-already-setup-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/someone-has-already-setup-teams.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **billkau**

**Comment by msbemba** [comment] 2021-06-24 16:54
@ks2018ks Thank you for your feedback. You are correct, the document talks about a different issue.

In your case, the error usually appears if proper team licenses are not assigned to the end user. Let us know.

Thanks
Sri

**Comment by ks2018ks** [comment] 2021-06-24 16:59
Why do you mark it "Resolution" when it's not a Resolution?

**Comment by msbemba** [comment] 2021-06-24 17:01
@ks2018ks  This is the resolution for "Someone has already set up Teams for your organization" error in Microsoft Teams.
In your case the error is different.

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-09 11:11
@nam31 There are no changes required in the document as the error reported is different from what is discussed in the document.

Thanks
Sri

**Comment by nam31** [comment] 2021-07-14 18:33
@ks2018ks Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Closed by nam31** 2021-07-14 18:33 UTC
