### ISSUE TITLE
Content Needs upadate

### ISSUE THREAD

**Issue by jamilhaddadin** [MicrosoftDocs/OfficeDocs-Support#641] opened 2020-07-02 06:08 UTC
I have this problem (Happened very recently on Jul-2020) on my office 365, I believe the reason is correct because i have added Visio 2019 to my already existing installation but the fix is not relevant  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b77aae-c967-714a-c888-e4d451a02585
* Version Independent ID: d4fe8833-3567-c6f6-1b08-8cb5ac356c1a
* Content: [0x80041015 error when you start an Office program - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/0x80041015-start-office-program)
* Content Source: [Office/Client/office-suite-issues/0x80041015-start-office-program.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/0x80041015-start-office-program.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by simonxjx** [comment] 2020-07-02 08:04
Thanks for your comment. According to the article, the issue is already fixed in the updated Office 2013 Click-to-Run image in 2014.  So, the issue is also fixed in the later versions of Office.

**Closed by simonxjx** 2020-07-02 08:04 UTC

**Comment by jamilhaddadin** [comment] 2020-07-05 09:56
I have figured out what was the reason of my issue:
I already have MS365 subscription, I have word, excel, onenote... installed

I tried to add Visio but I used my personal license, this caused this issue; when I uninstalled it & followed the right process of acquiring Visio from the[ right channel](url
![image](https://user-images.githubusercontent.com/9879719/86530149-fca5a800-bebe-11ea-97a1-113d430ec488.png)
); everything was ok
